### ISSUE TITLE
Allow save to server

### ISSUE THREAD

**Issue by mikeamcbrien** [EllisLab/download-content#2]
I would like this plugin to also allow teh ability to 'save to server' when creating the file for download.   entering a path/filename to save to the server would be most excellent.

**Comment by derekjones** [comment]
In your use case, should identically named files overwrite existing, or be unique (date/time suffix for example)?

**Comment by mikeamcbrien** [comment]
In my instance, overwrite.  I could see how it would be handy to append a timestamp, prefix, suffix or similar to the file also.

**Comment by derekjones** [comment]
Implemented in 0def083
