### ISSUE TITLE
EE6 Compatibility - Getting error with 6.0.0

### ISSUE THREAD

**Issue by mcfarlandonline** [EllisLab/Download-Content#3]
Hi there, 

I'm new to this AddOn, but trying to run it in EE 6.0.0. I'm getting an error within my downloaded file (below). 
The rest of the desired entry content is included in the downloaded file, as expected.

```
<div class="err-wrap warn">
	<h1>Warning</h1>
	<h2>Class &#039;ExpressionEngine\Addons\DownloadContent\Download_content&#039; not found</h2>
	<p>ee/ExpressionEngine/Core/Autoloader.php, line 92</p>
	<ul>
		<li><b>Severity</b>: E_WARNING</li>
	</ul>
</div>
```

**Comment by intoeetive** [comment]
I am not able to replicate this issue as of EE 6.0.2
Closing this ticket, if you still have same error, please reopen

**Comment by mcfarlandonline** [comment]
Hi Yuri, 

I'm still getting errors in 6.0.2. The content I want to download shows up at the bottom of the page under these errors... 

Warning
Class 'ExpressionEngine\Addons\DownloadContent\Download_content' not found
ee/ExpressionEngine/Core/Autoloader.php, line 91

Severity: E_WARNING
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/legacy/helpers/download_helper.php, line 54

Severity: E_WARNING
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/legacy/helpers/download_helper.php, line 55

Severity: E_WARNING
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/legacy/helpers/download_helper.php, line 56

Severity: E_WARNING
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/legacy/helpers/download_helper.php, line 57

Severity: E_WARNING
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/legacy/helpers/download_helper.php, line 58

Severity: E_WARNING
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/legacy/helpers/download_helper.php, line 59

Severity: E_WARNING

**Comment by intoeetive** [comment]
The new release is getting this fixed: https://github.com/EllisLab/Download-Content/releases/tag/3.1.0

(and you might want to update your `index.php` file to have say `$debug = 0;` to avoid errors on front-end; unless you are in the development phase still)

**Comment by mcfarlandonline** [comment]
Thanks, Yuri! It's working for me now! Appreciate your help.
